# System-wide configs
global:
  api_endpoint: "https://api.ucloud.cn"
  public_key: "public_key"
  private_key: "private_key"
  # This exporter listens at this port
  mertric_port: ":8080"
  # Scrape ucloud api every 10 secs
  interval: 10
  # If enabled, it will not change bandwidth
  dry_run: false
  # Prints alert webhook body
  verbose: false

# A list of shareBandwidth to be monitored
targets:
    # shareBandwidthID
  - name: "bwshare-q012a"
    # shareBandwidth zone
    region: "cn-bj1"
    # set to 100 when exiting
    default_bandwidth: 100
    # raise bandwidth by 20%
    raise_ratio: 20
    hard_limit:
      # upper limit of this shareBandwidth
      up_limit: 200
      # lower limit of this shareBandwidth
      down_limit: 50
    # bandwidth will be set at max(varied_limits..) * (100 + raise_ratio)%
    varied_limits:
      - "max_over_time(total_bandwidth_usage[30m] offset 7d)"
      - "max_over_time(total_bandwidth_usage[30m] offset 1d)"
      - "max_over_time(total_bandwidth_usage[10m])"
