# System-wide configs
global:
  api_endpoint: "https://api.ucloud.cn"
  public_key: "public_key"
  private_key: "private_key"
  # This exporter listens at this port
  mertric_port: ":8080"
  # Scrape ucloud api every 10 secs
  interval: 10

# A list of shareBandwidth to be monitored
targets:
    # shareBandwidthID
  - name: "bwshare-q012a"
    # set to 100 when exiting
    default_bandwidth: 100
    # upper limit of this shareBandwidth
    up_limit: 200
    # lower limit of this shareBandwidth
    down_limit: 50
    # shareBandwidth zone
    region: "cn-bj1"
    # turn up bandwidth by 30MB every time
    up_step: 30
    # turn down bandwidth by 10MB every time
    down_step: 10
